name: Build and deploy ASP.Net Core app to Azure Web App - medshift-api-demo

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/main_medshift-api-demo.yml"
  workflow_dispatch:

env:
  PROJECT: api/src/MedShift.Api/MedShift.Api.csproj
  DOTNET_VERSION: "9.0.x"
  AZURE_WEBAPP_NAME: medshift-api-demo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT }}

      - name: Publish
        run: dotnet publish ${{ env.PROJECT }} -c Release -o ${{ env.DOTNET_ROOT }}/myapp --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4E9896E58DFB4C1F90B41C3236367B41 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B10F7674EDBB44AFA3007FEC4C1E9B76 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_18C958CCB5AF4132AFD214DEE8ACE860 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
